### ISSUE TITLE
ImportError: cannot import name 'SortImports' from 'isort'

### ISSUE THREAD

**Issue by PentalimbedPuss** [willcrichton/inliner#10]
Traceback (most recent call last):
  File "E:/Programming/Python/Projects/pandaTest/main.py", line 2, in \<module\>
    import ECS
  File "E:\Programming\Python\Projects\pandaTest\ECS.py", line 3, in \<module\>
    from inliner import inliner
  File "D:\Program Files\Python\lib\site-packages\inliner\__init__.py", line 1, in \<module\>
    from .inliner import Inliner
  File "D:\Program Files\Python\lib\site-packages\inliner\inliner.py", line 7, in \<module\>
    from .passes import (PASSES, CleanImportsPass, CopyPropagationPass,
  File "D:\Program Files\Python\lib\site-packages\inliner\passes\__init__.py", line 6, in \<module\>
    from .clean_imports import CleanImportsPass
  File "D:\Program Files\Python\lib\site-packages\inliner\passes\clean_imports.py", line 2, in \<module\>
    from isort import SortImports
ImportError: cannot import name 'SortImports' from 'isort' (D:\Program Files\Python\lib\site-packages\isort\__init__.py)

Seems to be a version error?

**Comment by cdecompilador** [comment]
Here having the same issue
